language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.3

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17  
  
  licenses:
    - '.+'
  
  before_script:
    - chmod +x gradlew

  script:
    - chmod +x ./gradlew
    - ./gradlew assembleDebug assembleRelease
  
  before_install:
    - chmod +x gradlew
 
